/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Model {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'materialConfig' : string,
  'polygonCount' : bigint,
  'description' : string,
  'boneCount' : bigint,
  'category' : string,
  'textureInfo' : string,
}
export interface ModelInput {
  'id' : string,
  'name' : string,
  'tags' : Array<string>,
  'materialConfig' : string,
  'polygonCount' : bigint,
  'description' : string,
  'boneCount' : bigint,
  'category' : string,
  'textureInfo' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'deleteModel' : ActorMethod<[string], undefined>,
  'filterModelsByName' : ActorMethod<[string], Array<Model>>,
  'getAllModels' : ActorMethod<[], Array<Model>>,
  'getCategories' : ActorMethod<[], Array<[string, bigint]>>,
  'getModel' : ActorMethod<[string], Model>,
  'getModelCount' : ActorMethod<[], bigint>,
  'listByCategory' : ActorMethod<[string], Array<Model>>,
  'saveModel' : ActorMethod<[ModelInput], undefined>,
  'searchModels' : ActorMethod<[string], Array<Model>>,
  'updateMaterialConfig' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];